<?php

namespace AppBundle\Repository;

/**
 * referentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class referentRepository extends \Doctrine\ORM\EntityRepository
{
}
