<?php

namespace AppBundle\Repository;

/**
 * userProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
