<?php

namespace AppBundle\Repository;

/**
 * bibliographRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bibliographRepository extends \Doctrine\ORM\EntityRepository
{
}
