<?php

namespace AppBundle\Repository;

/**
 * bibliographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bibliographyRepository extends \Doctrine\ORM\EntityRepository
{
}
