<?php

namespace AppBundle\Repository;

/**
 * referenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class referenceRepository extends \Doctrine\ORM\EntityRepository
{
}
